### ISSUE TITLE
Somehow it fails while parsing google reader app, though its present on market.

### ISSUE THREAD

**Issue by rtdp** [chadrem/market_bot#13]
e.g. for this url - https://play.google.com/store/apps/details?id=com.google.android.apps.reader&hl=en

it fails saying - 

    NoMethodError: undefined method `elements' for nil:NilClass
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/market_bot-0.9.1/lib/market_bot/android/app.rb:23:in `parse'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/market_bot-0.9.1/lib/market_bot/android/app.rb:169:in `update'
        from (irb):32
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.12/lib/rails/commands/console.rb:47:in `start'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.12/lib/rails/commands/console.rb:8:in `start'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus/rails.rb:134:in `console'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:116:in `block in command'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:103:in `fork'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:103:in `command'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:80:in `block (3 levels) in go'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:80:in `fork'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:80:in `block (2 levels) in go'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:73:in `each'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:73:in `block in go'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:62:in `loop'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:62:in `go'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:78:in `block (3 levels) in go'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:78:in `fork'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:78:in `block (2 levels) in go'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:73:in `each'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:73:in `block in go'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:62:in `loop'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:62:in `go'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:78:in `block (3 levels) in go'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:78:in `fork'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:78:in `block (2 levels) in go'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:73:in `each'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:73:in `block in go'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:62:in `loop'
        from /home/rtdp/.rvm/gems/ruby-2.0.0-p0/gems/zeus-0.13.3/lib/zeus.rb:62:in `go'

**Comment by chadrem** [comment]
@rtdp I don't know if this issue is resolved, but I can't test since the URL you provided doesn't seem to work.  If you are able to still reproduce this issue then please re-open the issue.  Thank you.

**Comment by rtdp** [comment]
ohh @chadrem  it seems that URL is not accessible form incognito, but I can see that Google Reader application when I am logged in with my account.

Probably because Google Reader is deprecated and offline, and I have it in my apps which makes it accessible to me when logged in.
