### ISSUE TITLE
Bug in parsing developer apps

### ISSUE THREAD

**Issue by puzanov** [chadrem/market_bot#25]
Hi 

There is a bug when I try to get apps by developer. 

developer = MarketBot::Android::Developer.new('Best Quotes Ever')
developer.update
puts "Results found: #{developer.results.count}"

Output is Results found: 168

But this account has only 6 apps: https://play.google.com/store/apps/developer?id=Namba

**Comment by chadrem** [comment]
@puzanov I am going to close this issue due to inactivity.  Please re-open it if there is still a problem.
