### ISSUE TITLE
Search is limited to 420?

### ISSUE THREAD

**Issue by alexdelbosque** [chadrem/market_bot#32]
I kept doing several searches and all say 420, when i assume there are more than 420.

tried modifying the max pages on the search query but it didnt increase results

**Comment by cedricbousmanne** [comment]
Same problem here.

I'd love to know if there is a workaround

**Comment by chadrem** [comment]
i don't know a workaround since this isn't a market   issue.  The issue is Google blocks the request for more data.  One possible workaround is to purchase commercial data and build your own search engine on top of it.
