### ISSUE TITLE
rank offsets for developers based on 24 results/page vs 12

### ISSUE THREAD

**Issue by nicholas-lonsinger** [chadrem/market_bot#4]
When you pass in the min/max rank to the developers object, it is using the rank_to_page function of the leaderboard, and this is based on 24 results for a page.

So if I ask for items 13-24, I end up getting items 1-12 again, since it is thinking that is page 1.

**Comment by chadrem** [comment]
Closing this issue since the v1.0 API won't have a rank offset feature.
