### ISSUE TITLE
Got unexpected response code: 0

### ISSUE THREAD

**Issue by Vivekban** [chadrem/market_bot#40]
I am trying to get data for a app by running script.
app = MarketBot::Android::App.new('jp.konami.pesclubmanager')
app.update

 But i am always getting error. 
C:/Ruby21/lib/ruby/gems/2.1.0/gems/market_bot-0.14.0/lib/market_bot/android/app.rb:191:in `handle_response': Got unexpected response code: 0 (MarketBot::ResponseError)
	from C:/Ruby21/lib/ruby/gems/2.1.0/gems/market_bot-0.14.0/lib/market_bot/android/app.rb:156:in `update'
	from test.rb:6:in `<main>'

**Comment by chadrem** [comment]
@Vivekban I tried the code you pasted and it works for me.  It looks like you are getting a HTTP response code 0 instead of the usual 200.  Unfortunately I don't know why since I can't reproduce it on my end.  Did Google block your IP address?  It's possible you hit one of their limits.

**Comment by SanjayYadav90** [comment]
hi chadrem ,

How to list all apps on a page with app logo, app url, Rate etc.
