### ISSUE TITLE
how to get attibutes

### ISSUE THREAD

**Issue by syllogismus** [chadrem/market_bot#41]
hi,

im running your example(s), but all im getting is this:

{:stars=>"3.7", :title=>"Talking Donkey", :price_usd=>"Free", :developer=>"Dexati", :market_id=>"com.km.voice.talkingdonkey", :market_url=>"https://play.google.com/store/apps/details?id=com.km.voice.talkingdonkey&hl=en"}

how do i get all the other attributes?

thx

**Comment by aandis** [comment]
You are probably doing a `search` which returns just the attributes you mentioned. To get other detailed attributes you need get the `market_id` and initialize `AndroidApp` with that id. Something like 

``` ruby
id = search_result[:market_id]
app = MarketBot::Android::App.new(id)
app.update
puts app
```

**Comment by chadrem** [comment]
@syllogismus Hopefully you have this working based on the comment from @aandis.  If not feel free to re-open this issue.
