### ISSUE TITLE
Downloading APK for playstore

### ISSUE THREAD

**Issue by gowtham1984** [chadrem/market_bot#47]
Is there a way to build capability to download the APK file or generate a download link to APK with marketID or play store URL as input

**Comment by chadrem** [comment]
You can't download apk files with this gem.  Most likely it isn't possible with screen scraping so you would need to reverse engineer the play store app.

**Comment by gowtham1984** [comment]
Could you please explain the process of reverse engineering the play store
app to get the apk file if you are aware of it.

Thank you

**Comment by chadrem** [comment]
Sorry I can't provide such information.
