### ISSUE TITLE
Please bring back category_url for app

### ISSUE THREAD

**Issue by Halt** [chadrem/market_bot#50]
Category url is uniq key to link applications to categories. Please bring it back to app attributes.

**Comment by chadrem** [comment]
Thanks for the feedback!  I'll add it back in the next 24 hours or so.

**Comment by chadrem** [comment]
@Halt The latest master code has category_url back in it.  Let me know if you have any other feedback.  I'm working toward cleaning up stabilizing the API for v1.0.
