### ISSUE TITLE
What's new is nil

### ISSUE THREAD

**Issue by elprogrammer** [chadrem/market_bot#51]
app.whats_new is nil
ruby output:
> getapp.rb:7:in `+': no implicit conversion of nil into String (TypeError)
	from getapp.rb:7:in `<main>

my code:

> require 'rubygems'
require 'market_bot'
require 'json'
app = MarketBot::Play::App.new('com.ketchapp.stack')
app.update
puts 'whats_new: ' + app.whats_new

**Comment by chadrem** [comment]
:whats_new was never implemented in v1.0.0. I have added it back in v1.0.2. Give it a try and let me know if it works for you.
