### ISSUE TITLE
Scraper fails when the app has no rating. 

### ISSUE THREAD

**Issue by matthieua** [chadrem/market_bot#52]
Here is an example:
https://play.google.com/store/apps/details?id=com.forktech.landtokitchen

At this time, the app has no ratings and the scrapers crashes [here](https://github.com/chadrem/market_bot/blob/master/lib/market_bot/play/app.rb#L139).

The `div.rating-histogram` doesn't exist in this case.

Here is how I fixed it but it's pretty nasty [1cef1aa849f1f386a9dd3cf237d38f8357cc5ab5](https://github.com/matthieua/market_bot/commit/1cef1aa849f1f386a9dd3cf237d38f8357cc5ab5)

**Comment by chadrem** [comment]
@matthieua Thanks for letting me know about this! I just just released v1.0.3 with a modified version of your fix. No worries on the nasty bits... I've been meaning to clean up the parser code (break it into nice/small functions) now that the project has full test coverage.  I noticed you are a YC company (so is mine). Let me know if you are free to chat sometime... would like to hear how you are using Market Bot, how the business is going, etc.

**Comment by matthieua** [comment]
Thanks a lot Chad for fixing it! 

Absolutely, feel free to email me matthieu.aussaguel@gmail.com. We mainly use Market Bot to facilitate our submission process so it's not a very particular use case but it's been super useful! Happy to give you more details if you want :)
