### ISSUE TITLE
developer_id for app

### ISSUE THREAD

**Issue by Halt** [chadrem/market_bot#54]
hi chadrem. it is nice to have uniq developer_id property for app. it could be parsed without issues from application page.

**Comment by chadrem** [comment]
@Halt I haven't looked into it, but that sounds great. I'll convert this issue into a feature request and leave it open until the feature is built and a new gem is released. Do you have time to built and and add a test too? If so, just send me a pull request. Feel free to ask any question on the code if needed.

**Comment by chadrem** [comment]
@Halt The developer_id attribute has been merged into master thanks to @Simran1306 so I'm closing this issue.
