### ISSUE TITLE
adjust gem spec gem.executables

### ISSUE THREAD

**Issue by MadBomber** [chadrem/market_bot#55]
You bin directory is placed on the $PATH.  It contains some very generic file names.  If you intend these executables to be common utilities for the user, you should do something to "namespace" them to your gem.  For example consider market_bot_console and market_bot_setup, etc.  Otherwise you should remove them from your gem.executables parameter.

Dewayne
  o-*

**Comment by chadrem** [comment]
@MadBomber Thanks for pointing this out!
