### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by swrobel** [chadrem/market_bot#56]
Love the gem, don't want to sound ungrateful, but changelogs are helpful :)

http://keepachangelog.com/

**Comment by chadrem** [comment]
@swrobel glad to hear you love the gem. I'll take the changelog idea into consideration for future releases. Please let me know if you have time to contribute to features & bug fixes.

**Comment by chadrem** [comment]
@swrobel just a heads up... I added the changelog as you requested.
