### ISSUE TITLE
Is it possible to include review.id in app.reviews?

### ISSUE THREAD

**Issue by tom-wolters** [chadrem/market_bot#65]
To be able to compare reviews, it would be nice to receive the Review.id (app.reviews). Is that possible?

**Comment by chadrem** [comment]
Not sure if it’s possible as the original review code was a contribution via pull request and I’m not familiar with what data google publishes for reviews. It sounds like a useful feature though. Do you have time to investigate and add it? Let me know if you have any questions on the codebase.

Alternatively, you could look into building a review fingerprint that acts like an id in your app. Perhaps something like concatenate some is the review data (review text, author name, time stamp, app id) and then md5 it. I suspect this hack would work reasonably well for a lot of use cases. 

  -Chad

**Comment by tom-wolters** [comment]
I think it's possible as the reviewId is in the permalink class of the HTML page. I am unable to test my contribution easily. Perhaps I can make a PR, but are you able to see if the review_id is added to a review?

**Comment by tom-wolters** [comment]
That should be possible. There's an reviewId in the permalinks class. I'll create a pull request.
